# Generated by Django 2.0.5 on 2018-05-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='file',
            new_name='form',
        ),
        migrations.AlterField(
            model_name='form',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
